from itertools import groupby


def kompresja(tekst):
    grupy = groupby(tekst)
    tekst_skompresowany = [(sum(1 for _ in grupa), znak)
                           for (znak, grupa) in grupy]
    return tekst_skompresowany


def dekompresja(tekst_skompresowany):
    return "".join(znak*liczba for (znak, liczba) in tekst_skompresowany)


print(kompresja("111000222334455555"))
print(kompresja("suuuuuuperuuuuuu"))
print(dekompresja(
    [(3, '1'), (3, '0'), (3, '2'), (2, '3'), (2, '4'), (5, '5')]))
print(dekompresja(
    [(1, 's'), (6, 'u'), (1, 'p'), (1, 'e'), (1, 'r'), (6, 'u')]))

a = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum lectus lorem, sagittis at tempus aliquet, mollis facilisis quam. Nulla et velit lorem. Nunc sed pharetra justo. Praesent placerat enim at urna semper consequat. Aliquam suscipit dui a mi blandit varius. Pellentesque odio mi, placerat quis elit in, aliquet ultrices tortor. Vestibulum accumsan venenatis justo eget consequat. Donec sed dolor blandit, semper leo in, lacinia libero.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc mattis faucibus maximus. Fusce eget dignissim metus. Morbi malesuada dui ut molestie imperdiet. Donec malesuada enim eros, vel auctor ex auctor at. Morbi posuere posuere turpis, vitae scelerisque mauris tempus et. Donec a eros eu orci interdum tristique nec eleifend risus.

Aliquam at suscipit velit, at condimentum quam. Maecenas luctus varius eros quis dictum. Nam mollis massa non finibus malesuada. Aliquam quis sem pulvinar, ullamcorper massa eu, egestas arcu. Nulla rutrum efficitur fermentum. Quisque sagittis orci non efficitur faucibus. Etiam nec lorem rhoncus, consequat nisl quis, finibus libero. Sed semper rhoncus felis, nec sodales diam maximus ut. Praesent ac erat urna. Proin sollicitudin purus at odio facilisis, vel accumsan nibh pretium. Fusce tincidunt felis non cursus vestibulum. Suspendisse potenti. Etiam iaculis semper porttitor. Fusce sagittis urna nisi, at ultricies ipsum tempor eget. Nam vulputate dui tortor, non iaculis risus hendrerit vel. Mauris nec vestibulum nisl, vitae volutpat ante.

Maecenas iaculis urna sit amet felis luctus vehicula a vel eros. Donec elementum ut erat et consequat. Praesent et mi efficitur ex rhoncus vulputate. Donec vitae odio sodales, vestibulum neque eleifend, porta ante. Quisque sagittis leo quis leo molestie, non posuere velit finibus. Suspendisse potenti. Maecenas urna erat, sodales tempus viverra in, accumsan commodo nulla. Sed porttitor sodales nulla eu egestas. Phasellus nec erat ut eros condimentum scelerisque egestas eu odio.

Donec dolor purus, lobortis ac mi ac, feugiat dapibus enim. Nulla ut venenatis nunc. Nulla aliquet sed risus vel venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id eleifend leo. Vestibulum porttitor lectus non felis tincidunt mattis. Ut ultricies, ligula eu facilisis mollis, est elit hendrerit nulla, at ultricies orci odio at dui. Aenean orci est, pretium non nisl quis, volutpat tincidunt sem. Quisque euismod semper tellus ultricies fermentum. Vivamus et luctus dolor. Etiam in placerat augue, eget dignissim lectus.

Donec lobortis nunc consectetur felis commodo ullamcorper. Aliquam imperdiet urna massa, sit amet egestas orci mollis a. Nulla accumsan urna in ipsum sodales, at ultricies turpis maximus. Integer rhoncus urna commodo purus pharetra, id aliquam tortor venenatis. In et elit metus. Donec ac lectus lorem. In hac habitasse platea dictumst. Curabitur vestibulum ornare mauris. Nulla sollicitudin, nunc et sagittis commodo, orci lorem auctor dolor, ac varius nibh purus eget lacus. Donec enim massa, sagittis eget bibendum nec, aliquam aliquam ante. Integer vel leo sed neque scelerisque iaculis id id enim. Aliquam fermentum sem non sem sodales sagittis efficitur vel turpis. Praesent in ligula consectetur lacus elementum imperdiet eu vitae arcu. Pellentesque molestie venenatis mi in egestas. Proin mattis orci sit amet facilisis malesuada. Quisque ornare neque nec ligula hendrerit, ut posuere orci facilisis.

Vestibulum placerat ligula eu mi posuere sagittis. Integer fermentum purus et mauris ultricies ultrices. Aliquam efficitur rutrum nulla, vel faucibus urna fringilla et. In hac habitasse platea dictumst. Proin ornare eleifend odio tempus malesuada. Duis ultrices pellentesque mauris. Aliquam ut velit nec enim iaculis lacinia vitae ac odio. Sed varius fermentum sodales.

Ut iaculis arcu non scelerisque euismod. Etiam imperdiet nibh felis, ac iaculis ante dignissim eu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut mauris dui, tempus et dolor vel, convallis sollicitudin urna. Maecenas eleifend condimentum rutrum. Nunc euismod, odio eget eleifend ullamcorper, purus velit vehicula erat, ut blandit lorem sem eget augue. Proin luctus velit quis tortor blandit lobortis. Praesent vel libero sodales, congue nulla at, mollis ante. Phasellus quis varius justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris nec lorem vel lectus fermentum rutrum in in massa. Nulla varius, magna convallis ornare sodales, ex magna condimentum lectus, ac tempor lectus velit et nisi.

Sed aliquet mollis malesuada. Pellentesque a nunc pharetra magna feugiat finibus non sed dui. Etiam nec odio eu purus porta ornare ut non justo. Cras in lacus non lorem aliquet varius. Praesent diam tortor, interdum vel tortor sed, fermentum facilisis sem. Pellentesque feugiat massa vitae mi ultricies, at tempor est congue. Pellentesque dapibus mauris nec urna accumsan, vel laoreet nibh interdum. Ut eu dignissim metus. Sed eget odio et risus hendrerit viverra. Pellentesque accumsan tellus ut mauris viverra scelerisque. Donec molestie porta condimentum. Suspendisse ultricies accumsan risus, vel congue nunc pellentesque tristique. Nulla aliquet non orci semper mattis.

Fusce fermentum eleifend mi, sed laoreet dui porttitor et. Praesent varius laoreet enim, ac gravida nunc malesuada nec. Nulla quis scelerisque metus. Morbi accumsan leo et tellus pretium ornare. In ut arcu a erat pharetra pellentesque. Maecenas tellus nisl, maximus ac arcu ut, laoreet laoreet nisi. Praesent lacinia magna et semper eleifend. Aliquam ex mauris, accumsan at enim vitae, gravida vestibulum lectus. Praesent nec placerat tellus. Nunc libero ligula, gravida ut enim sit amet, interdum sollicitudin metus.

Praesent sapien orci, ornare ac mauris non, blandit molestie dui. Nunc sed velit risus. In leo neque, ultricies quis tortor sed, rhoncus vehicula ipsum. In eleifend suscipit mi sed molestie. Pellentesque enim felis, congue sed massa at, volutpat egestas nunc. Nulla rhoncus nibh sit amet velit tincidunt ullamcorper. Sed eu vestibulum est. Maecenas pulvinar dictum ante. Mauris in dolor sed magna mattis dapibus.

Vivamus non ligula turpis. Etiam lorem sapien, condimentum eu dapibus in, suscipit ut eros. Nulla rhoncus odio vulputate est finibus accumsan. Integer quis est id metus placerat ultrices. Maecenas nec imperdiet odio. Nullam consequat sollicitudin pharetra. Integer quis volutpat nisi, eget tincidunt ante. Fusce et maximus arcu, id suscipit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sed imperdiet risus.

Quisque enim urna, imperdiet vitae magna a, vehicula vestibulum justo. Nam cursus mi pharetra, malesuada nibh eget, viverra est. Curabitur eget pellentesque nunc. In ullamcorper arcu quis congue cursus. Pellentesque ut euismod orci. Mauris nec orci mauris. Etiam sed est dui.

Aenean ut finibus lacus. Nam tincidunt turpis sit amet tellus faucibus, eget efficitur velit luctus. Donec eget orci nec ex commodo fringilla dapibus sed sem. Nunc in neque justo. Nulla pellentesque ante sed dui molestie semper. Duis faucibus felis vel gravida luctus. Nulla diam justo, blandit non massa sit amet, tincidunt convallis diam.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut eu sapien eu elit dignissim euismod. Nunc ultrices mauris vitae nulla egestas, sed mollis metus rutrum. Proin sed massa felis. Phasellus eget mauris turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices purus viverra tincidunt venenatis. Duis aliquam aliquam lorem non eleifend.

Donec non magna enim. Aliquam erat volutpat. Ut dapibus libero tortor, ut lacinia urna efficitur vel. Praesent sollicitudin nunc at orci auctor volutpat. Mauris ac porttitor sem. Pellentesque ac fermentum orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum bibendum odio laoreet ipsum ultrices pulvinar. Nullam ultricies elementum magna, sit amet placerat massa sodales quis. Integer rutrum rutrum nisl, sed finibus augue euismod quis.

Nunc sed felis nibh. Morbi erat magna, cursus ut dapibus sed, pellentesque eget sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer dictum mollis nisi, vitae consequat libero ullamcorper non. Vestibulum rutrum suscipit mi, ut sagittis dolor placerat at. Donec in justo vestibulum, aliquet velit et, tincidunt mauris. Proin euismod enim augue, nec rutrum arcu feugiat ac. Nunc fermentum tortor lectus, maximus lobortis justo aliquet sit amet. Cras faucibus, ante vitae tincidunt aliquet, lectus dolor euismod urna, et facilisis enim sapien non enim.

Aliquam sagittis porta laoreet. Phasellus malesuada interdum risus, non porta massa pretium in. In convallis fermentum lorem non rhoncus. Integer consectetur, odio at ultrices blandit, ex libero molestie elit, nec gravida felis ex non sapien. Proin vitae cursus nunc. Aliquam maximus lectus a imperdiet vulputate. Nam ac aliquet arcu. Sed non egestas quam. Nam enim leo, maximus vestibulum pretium ut, interdum id arcu. Cras sed elit placerat, dapibus orci a, sodales orci. Praesent lobortis eu libero a blandit.

Ut neque urna, viverra eget mattis vel, rutrum a felis. Etiam nec mi nisi. Maecenas auctor dui nec enim ultricies tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec ut elit sit amet sapien mollis laoreet ut nec nisi. Mauris sed iaculis nisi, eu ultrices mauris. Donec accumsan dapibus iaculis. Suspendisse ac urna lectus. Cras ut mauris ultrices, placerat enim quis, suscipit magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nullam vitae finibus ipsum. Aliquam id nibh turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque luctus, libero non commodo accumsan, massa purus luctus urna, et dignissim turpis dui nec justo. Donec accumsan, quam eget tincidunt laoreet, est mi sagittis augue, ut tincidunt metus velit at justo. Suspendisse iaculis nisl ac arcu vulputate egestas. Nam posuere elementum erat, at elementum nisi tincidunt et. In faucibus velit vitae sem hendrerit, sit amet bibendum massa condimentum. Sed cursus, lacus sit amet placerat placerat, orci dui lacinia nisi, et vulputate lorem justo id justo. Curabitur non lobortis dolor. Duis eu turpis vehicula, lobortis magna vitae, dapibus turpis. Donec egestas, urna at ornare imperdiet, diam lorem pulvinar dolor, sed condimentum lorem augue eget est. Duis suscipit urna vel rutrum elementum.

Ut tristique dapibus faucibus. Nam placerat a purus at tempor. Aenean sed lorem eu erat commodo rhoncus. Maecenas magna turpis, vulputate non ante ut, ornare pellentesque lectus. Aenean risus magna, euismod eget justo et, tempor posuere dolor. Nunc non sapien libero. Nunc at mi nunc. Donec et augue dolor. Mauris finibus dolor eros, sed consequat justo viverra eu.

Cras tellus sem, lacinia quis fringilla in, placerat vel leo. Vestibulum eu massa at augue ornare lobortis. Sed a nisl et orci elementum consequat in sit amet arcu. Vestibulum vitae elit eget purus fermentum rhoncus a in dolor. Donec laoreet, tortor vel congue tempus, est augue imperdiet tellus, et rhoncus erat magna eu ligula. Nunc feugiat purus ac felis vulputate, ut cursus lacus ultrices. Mauris rutrum felis a purus viverra, at finibus ex ornare. Phasellus et varius dui.

Morbi sagittis quam tristique enim interdum mollis. Nunc eget lorem ac nunc porta porttitor. Mauris eleifend neque dolor, a efficitur felis fringilla sit amet. Cras lacinia fringilla nunc sit amet scelerisque. Pellentesque sem felis, tempor id eros tincidunt, rutrum ornare lacus. Etiam congue urna vel diam ullamcorper tincidunt. Donec ac consequat mauris. Nulla facilisi. In accumsan ex ac urna condimentum vestibulum. Praesent elementum vestibulum risus ut vehicula. Sed auctor lobortis eros a pharetra. Praesent imperdiet magna lobortis ligula ultrices, eu venenatis purus mollis. Aliquam mauris nulla, placerat sed est eget, cursus imperdiet enim. Curabitur est tortor, placerat vel hendrerit quis, vehicula ut nisl. Donec ut congue nisi. Nam ac venenatis eros.

Sed elit lectus, luctus eget convallis nec, tincidunt at risus. In id arcu vel ipsum sagittis posuere ac et nisl. Ut auctor quam sed leo rutrum, maximus maximus diam egestas. Fusce ornare est vitae porta pulvinar. Nam sed convallis nunc. Cras fringilla a nisl et consectetur. Donec vitae tristique augue.

Vestibulum quis pharetra arcu. Praesent est nisl, fringilla eu risus in, lacinia scelerisque justo. Donec condimentum elementum ligula sed ornare. Sed bibendum, arcu in lobortis aliquam, turpis metus egestas sapien, sit amet fringilla nibh purus eu libero. Aliquam gravida, elit ac sollicitudin auctor, velit lectus vulputate risus, sit amet congue lorem purus a mi. Curabitur porttitor urna ut nisl scelerisque sagittis. Morbi lobortis sem in quam euismod ultricies. Curabitur vel accumsan ligula, sit amet porttitor mauris. Nam ante sapien, posuere sed orci non, rutrum tristique risus. Curabitur nisl massa, rhoncus vestibulum facilisis at, tempus et dolor. Fusce molestie est sit amet arcu gravida rhoncus.

Suspendisse sit amet rhoncus urna. Vivamus volutpat risus ut mauris semper placerat. Donec lacinia sollicitudin luctus. Curabitur eu sapien accumsan, mollis nisi non, luctus augue. Maecenas maximus, urna nec ultricies semper, magna elit faucibus nibh, sit amet dapibus arcu velit ac urna. Nullam ac congue leo, quis volutpat enim. Nunc vestibulum imperdiet odio in accumsan. In blandit mauris a sodales hendrerit. Phasellus placerat ligula eu est malesuada tristique. Sed sagittis ipsum in velit lobortis, eu imperdiet est placerat.

Aenean imperdiet, nisi in bibendum venenatis, diam dui congue tortor, vitae condimentum augue mauris blandit justo. Cras consequat vehicula euismod. Fusce ultrices nunc vehicula gravida interdum. Proin condimentum nunc dui, vel aliquet tellus lobortis at. Proin consequat hendrerit leo, a sollicitudin dolor mollis nec. In scelerisque mauris quis sem semper, eget convallis ligula imperdiet. In venenatis consectetur ultricies. Fusce eu purus ac nunc fermentum laoreet vitae at est. Pellentesque sit amet nisi ac ex consequat sollicitudin. Donec maximus nulla vel dui fringilla, in pretium nunc bibendum. Suspendisse molestie velit dolor, et malesuada enim pulvinar nec. Suspendisse urna orci, dictum vel ipsum vitae, sagittis commodo turpis.

In scelerisque pellentesque ligula, eget placerat elit viverra vitae. Aenean venenatis laoreet ante, at auctor purus imperdiet imperdiet. Sed feugiat id orci ac tempor. Mauris euismod tristique enim quis pretium. Fusce aliquam orci enim, et sagittis massa dapibus eu. Quisque hendrerit neque tortor, non finibus nisl aliquam id. Cras malesuada molestie neque. Vivamus euismod dignissim porta. Nulla at ex pharetra, egestas metus sit amet, pharetra urna. Morbi ullamcorper lobortis augue at pretium.

Morbi fringilla dolor sit amet sapien commodo, eget sodales nibh tempus. Mauris pharetra lobortis neque, vitae pretium ligula viverra vel. Donec vitae odio in nisi volutpat condimentum tincidunt vel est. Aenean id molestie neque. Nam feugiat sodales mi non dignissim. Etiam gravida, ligula at convallis placerat, erat magna dapibus est, id efficitur libero erat in nunc. Mauris consequat velit vitae porta iaculis. Pellentesque at eros non massa tincidunt feugiat. Nam ipsum diam, luctus sit amet ullamcorper sed, fringilla nec nunc. Curabitur sodales risus a lectus lacinia blandit eget id lorem. Morbi augue sapien, vulputate sed ullamcorper a, lobortis hendrerit leo. Suspendisse eget mi nisl. Nulla venenatis faucibus lacus id molestie. Proin porta ipsum in vulputate tincidunt. Nam placerat tellus elit, sit amet pharetra purus dignissim et. In rhoncus sollicitudin pulvinar.

Ut suscipit odio sem, facilisis condimentum lectus faucibus id. Nulla bibendum purus ac odio volutpat, id efficitur eros vehicula. Aliquam vestibulum sapien vitae massa facilisis, sed suscipit enim venenatis. Ut efficitur, odio nec rhoncus imperdiet, dui ipsum molestie erat, vitae mattis velit leo id nisi. Suspendisse mollis ligula et neque aliquet, et finibus turpis cursus. Nullam pretium ante egestas dui aliquet tristique. Cras in ornare velit. Maecenas at ligula lectus. Morbi eu nisl quis eros maximus pharetra at vitae justo. Ut at nibh ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus enim in sollicitudin sollicitudin. Vivamus vel leo id eros tincidunt fermentum nec ac magna. Maecenas ex dui, porta ut lorem nec, pellentesque scelerisque erat. Fusce sit amet est sollicitudin, pharetra lectus sed, tincidunt leo.

In hac habitasse platea dictumst. Aliquam ultrices enim nec tincidunt sollicitudin. Donec nec leo arcu. Morbi accumsan id neque ac posuere. Nam mattis porta turpis ut dignissim. Curabitur eu lectus suscipit, lobortis risus a, vulputate urna. Praesent sollicitudin massa ut lectus lacinia blandit nec ut turpis. Morbi metus orci, vulputate ac tincidunt vel, consectetur nec sapien. Ut nunc mi, dictum a scelerisque quis, pellentesque et purus. Maecenas commodo neque sit amet urna sagittis, eu dignissim nulla lobortis. Mauris id mauris tellus. Integer a augue convallis libero aliquam facilisis nec quis felis. Maecenas mollis nisi libero, ut venenatis dolor maximus eget. Mauris congue enim ligula, et auctor sem malesuada eget.

Ut non rutrum odio. Morbi congue nulla at turpis euismod aliquet. Pellentesque sagittis pretium nisl, sed varius justo faucibus ut. Aenean convallis ornare lacus, sodales pellentesque mi finibus vel. Aliquam non interdum diam. Integer sed vulputate arcu. Nam gravida sollicitudin magna nec porta. Vestibulum gravida mattis quam, vel dictum augue blandit auctor. Cras tristique mauris massa. Vestibulum eu mollis justo, in faucibus mauris. Sed arcu ipsum, placerat vitae accumsan efficitur, ultricies placerat lacus. Aenean varius est tortor, eget varius orci pellentesque vehicula. Ut dignissim pretium urna. Donec sit amet augue vitae sapien tincidunt condimentum nec laoreet arcu. Curabitur egestas tellus eget sapien pulvinar, ac accumsan eros porttitor. Donec congue feugiat metus, vel bibendum dolor pellentesque sed.

Nunc scelerisque leo sit amet nisl dictum, eu rutrum lorem feugiat. Mauris maximus ultrices enim et molestie. Proin fermentum orci in odio aliquet sagittis. Ut cursus turpis in nisl pharetra dictum. Morbi in neque erat. Quisque feugiat aliquam lectus. Nam varius commodo elit, in euismod eros lacinia vitae. Proin in diam est. Sed malesuada libero ut rhoncus fermentum.

Donec hendrerit luctus malesuada. Aliquam cursus nibh ac velit rhoncus posuere. Duis ac augue id felis varius ultricies. Proin urna elit, mollis congue porta id, aliquam egestas felis. Mauris at sollicitudin turpis, vulputate cursus nulla. Quisque varius libero libero, in maximus turpis iaculis ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Nulla mollis facilisis volutpat. Nam auctor dolor augue, at gravida orci consectetur id. Nam nec leo urna. Praesent tristique luctus elit, eget congue eros faucibus et. Fusce eu felis sed velit bibendum ullamcorper at non est. Duis eget erat dolor. Integer at augue id elit aliquet placerat ac nec risus. Praesent eleifend libero et leo mattis efficitur. Nunc pellentesque sem non quam cursus sagittis. Suspendisse cursus eu magna vitae iaculis. Aenean quis felis fermentum, tincidunt ex a, viverra nisl.

Phasellus faucibus augue id massa tristique molestie. Vestibulum rhoncus egestas magna vel feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc mollis urna nec dictum rhoncus. Nulla nunc sem, porttitor sed blandit sit amet, ultrices quis nibh. Nullam mattis dictum diam in eleifend. Vivamus at enim vel eros tristique congue eget ac nisl.

Sed dictum felis in tortor iaculis, et blandit nibh pulvinar. Nulla scelerisque id enim in gravida. Nam fermentum enim a lectus viverra, vel cursus justo congue. Donec porta, augue at pulvinar tincidunt, lorem erat maximus augue, ut hendrerit tellus metus vel elit. Integer consequat nisi lectus, non elementum libero interdum eget. Ut tortor mi, fermentum ac eros a, mattis rutrum erat. Nam eu mi rutrum, viverra eros gravida, ullamcorper est. Curabitur fringilla dui ut risus sollicitudin imperdiet. Sed pretium leo sed consectetur ultrices. Morbi luctus dapibus metus id fringilla. Aliquam erat volutpat.

Vivamus molestie justo ac dui malesuada rhoncus. Suspendisse id enim arcu. Sed orci quam, hendrerit ut molestie egestas, mollis quis odio. In id varius justo. Morbi id quam sed magna convallis porttitor ac sit amet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec et finibus est. Mauris vel est vitae purus convallis placerat. Morbi at dolor ornare lectus bibendum varius. Mauris mauris leo, malesuada eu magna faucibus, viverra bibendum est. Integer sit amet imperdiet ligula, sit amet pellentesque lacus. In vulputate neque ac enim fermentum, eu finibus est congue. Integer porta velit ac arcu blandit, eget dapibus dui mattis. Quisque ligula est, hendrerit quis dui ut, ullamcorper commodo neque.

Aliquam suscipit tristique augue, volutpat accumsan ante maximus sed. Fusce condimentum purus eu pharetra pretium. Curabitur vehicula mauris eget vestibulum ultricies. Integer porttitor aliquam nunc et porttitor. Etiam ex lacus, mollis sit amet nisl at, maximus laoreet leo. Mauris posuere, sem tincidunt eleifend consectetur, mauris ex sodales metus, at molestie libero libero non dolor. In vitae quam vel augue viverra ultricies. Curabitur sodales suscipit sapien eget maximus. Proin placerat placerat dui, vitae mattis nunc vestibulum eget.

Nullam malesuada orci libero, sed ornare libero commodo vel. Maecenas dictum facilisis risus et convallis. Suspendisse nec cursus elit, dictum hendrerit neque. Donec gravida ligula vel sem consectetur, at accumsan mauris tempor. Aenean accumsan felis nec finibus imperdiet. Vestibulum dignissim tincidunt tortor non egestas. Donec auctor, elit vel hendrerit facilisis, tellus massa fermentum sem, sed vehicula lorem urna sed ante. Donec ante nulla, blandit at maximus non, lobortis sed augue. Aliquam blandit sem sit amet bibendum accumsan.

Fusce aliquet mollis velit, et convallis mauris varius at. Maecenas orci justo, iaculis eu laoreet gravida, posuere ut elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque at quam id libero efficitur egestas. Nunc sed metus ac tellus ornare laoreet. Praesent vulputate sem vitae nisi fermentum aliquam. Vestibulum elementum hendrerit imperdiet. Etiam aliquet turpis purus, tempus tincidunt odio scelerisque sit amet. Nulla sed risus convallis ligula auctor placerat. Donec sed odio finibus, posuere turpis commodo, ullamcorper augue. Cras cursus nunc et urna malesuada, in efficitur metus porta. Integer semper sollicitudin dignissim.

Proin hendrerit a ante eget maximus. Morbi accumsan lacus eu eros aliquam, a accumsan erat auctor. Sed pellentesque blandit sapien in rutrum. Etiam ipsum nisi, hendrerit a euismod at, fringilla ornare lectus. Curabitur tincidunt porta elit, eget porttitor nisi commodo at. Mauris porta gravida eros id euismod. Curabitur enim orci, convallis eget rutrum tincidunt, vestibulum nec justo. Vivamus fermentum at felis quis consequat. Phasellus tempor felis vel enim imperdiet, at pellentesque risus consequat. Nulla odio nisi, placerat at odio in, dapibus scelerisque velit. Nam aliquet blandit mauris, sed tincidunt metus laoreet eget. Maecenas vitae volutpat nisl. In et odio ornare, tempus leo id, sollicitudin augue.

Aenean mi quam, congue non arcu a, luctus tempus enim. Vestibulum lectus ante, efficitur ac diam commodo, auctor vehicula mi. Quisque posuere mi in tortor venenatis condimentum. Sed cursus sapien sit amet eros varius, non ultrices erat suscipit. Mauris faucibus et ex non efficitur. Phasellus suscipit, magna nec vulputate volutpat, risus est convallis turpis, in pellentesque orci libero sed ligula. Nulla condimentum turpis vel aliquam tincidunt. Integer ac nisl ligula. Proin ut aliquam mi. Suspendisse potenti. Aenean semper cursus elementum. Nulla facilisi. Ut in aliquet massa. Pellentesque a tincidunt magna. Fusce ac nunc tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nullam mollis mauris nec diam tincidunt, quis pharetra dui vehicula. Nulla mattis dictum nibh eu iaculis. Pellentesque tempor viverra orci at ultricies. Sed tempus, nisi sit amet consectetur laoreet, sapien nulla efficitur nisi, sollicitudin lobortis nisl nunc iaculis libero. Sed fringilla a nulla sed interdum. Quisque eleifend pulvinar lobortis. Cras fermentum mollis ante. Pellentesque sagittis auctor condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse et mi non sem feugiat congue nec aliquet nulla. Nullam faucibus bibendum lorem id ornare. Nunc interdum cursus sem et sagittis. Mauris nisl augue, efficitur et aliquet id, ullamcorper efficitur nulla. Praesent aliquam ante nec arcu ultricies, non ornare nulla elementum.

Suspendisse potenti. Sed commodo purus ac lorem congue placerat. Nulla quis sodales tortor. Duis non laoreet dolor. Donec ut ullamcorper magna, non bibendum quam. Sed finibus risus ut neque sodales, vel viverra nisl suscipit. Nulla eget euismod ante, ac fermentum dolor. Etiam dapibus sodales mi, at auctor massa tempor sed. Duis neque massa, ultrices at ante sed, viverra placerat ligula. Maecenas a posuere quam. Vivamus rutrum eros erat, at lacinia justo vehicula tempus. Quisque blandit, massa quis pharetra dictum, diam felis efficitur orci, eget egestas ipsum lacus at enim. Mauris odio mauris, viverra nec hendrerit eget, aliquam quis odio. Nulla vehicula luctus augue, sollicitudin lacinia sem pulvinar vitae.

In lacinia magna ac nunc pretium ultrices. Proin rutrum porttitor nulla. Phasellus vulputate iaculis augue non tempus. Sed maximus accumsan nisl ac consectetur. Etiam egestas at purus non blandit. Etiam ut dolor felis. Nunc tempus condimentum posuere. Morbi id metus consequat, mattis urna et, egestas tortor. Proin sollicitudin ipsum sit amet aliquet ullamcorper. Sed blandit tincidunt mauris. Nunc facilisis eros vel tellus congue sollicitudin. Donec aliquam ante eget turpis scelerisque auctor. Duis lacus elit, cursus pharetra auctor ut, tincidunt sed elit.

Pellentesque vel felis facilisis, varius magna non, gravida nisi. Etiam tempus felis non placerat malesuada. Nunc eu purus justo. Curabitur sit amet laoreet odio, ac lacinia arcu. Morbi vel dapibus purus, vitae vulputate nulla. In ligula magna, viverra in pretium sit amet, rutrum a erat. In pharetra finibus felis eget sodales. Nulla non facilisis urna, id iaculis velit. Etiam id nisi eu nisi sagittis dictum eget ornare sem. In vel felis ac eros accumsan eleifend.

Nunc porttitor aliquet laoreet. In hac habitasse platea dictumst. Etiam et velit nec nisl placerat auctor in non neque. Cras vehicula fringilla tellus, a mollis nisi rutrum et. Sed congue enim eu arcu sollicitudin, eget consequat orci interdum. Mauris sed ex magna. Integer lacinia eget lectus nec sollicitudin. Duis volutpat dui vel orci interdum hendrerit. Aliquam lectus urna, placerat tempus orci ac, consequat porttitor quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam nec nulla vitae odio euismod dapibus. Phasellus sagittis turpis nec ex cursus laoreet. Morbi finibus sem magna, et varius dolor eleifend et. In id ante ut enim elementum ullamcorper ac a nisl.

Maecenas bibendum ligula eget justo congue tristique vitae quis libero. Etiam sagittis mi at lacus euismod venenatis. Pellentesque posuere, leo ac blandit lacinia, ex metus placerat tortor, quis blandit odio nisi efficitur erat. Nunc iaculis augue nunc, et sollicitudin purus imperdiet suscipit. In rhoncus, quam interdum mollis maximus, neque risus tempus orci, ut condimentum sapien lacus scelerisque ipsum. Suspendisse rhoncus massa id libero dignissim tempus. Integer ut faucibus lorem. Donec vitae nibh vitae mi ornare semper.

Mauris convallis est vel urna placerat porta. Vivamus commodo posuere ante, eu dignissim tortor fermentum a. Nullam tempor, ligula ut vehicula molestie, risus dui congue felis, a convallis lacus magna pharetra tortor. Cras est sem, mollis non ornare quis, suscipit ut nisi. Sed tincidunt sapien tortor, et dignissim elit imperdiet ac. Proin auctor vitae dolor in ullamcorper. Donec semper consectetur nulla, a bibendum justo ultricies quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean volutpat, massa in porta vulputate, arcu mi faucibus odio, in ultricies purus turpis in nisl. Sed posuere venenatis felis eget tempus. Mauris lobortis augue augue, sed laoreet dui imperdiet ac. Vivamus quis bibendum nisi. Suspendisse luctus scelerisque rhoncus. Nam varius velit eget semper posuere. Nam efficitur vestibulum iaculis. Duis quis ullamcorper sapien.

Curabitur nisl arcu, gravida at efficitur eget, dapibus eu nunc. Mauris dictum velit vel massa aliquam, mattis venenatis tellus hendrerit. Ut et purus placerat nibh ullamcorper iaculis et ac turpis. Nunc placerat arcu augue, eu congue orci convallis pulvinar. Aliquam gravida est sed fringilla tristique. Phasellus vitae dui ullamcorper, ultrices velit sit amet, iaculis magna. Cras molestie, justo sit amet finibus maximus, justo risus congue velit, nec eleifend metus quam eget purus.

Praesent interdum nibh augue, at pharetra quam rhoncus sed. Proin pulvinar euismod eros et varius. Ut pellentesque rutrum rutrum. Duis dignissim dignissim placerat. Quisque fermentum ultrices interdum. Integer dapibus condimentum odio, nec lacinia lectus tincidunt vitae. Nullam pellentesque libero sit amet sagittis efficitur. Aliquam vel turpis sagittis, iaculis ligula eu, gravida ligula. Nam lobortis justo at libero bibendum varius.

Suspendisse auctor vestibulum felis, ut sagittis purus maximus pharetra. Ut a velit erat. Suspendisse at velit rhoncus, elementum sem at, blandit nisl. In commodo vitae risus et ultricies. Suspendisse potenti. Etiam ac porta dui. Sed elementum, nisi quis tempus sodales, nisl tellus dignissim magna, a dignissim mauris odio a enim. Maecenas urna sem, laoreet ut metus quis, tristique posuere orci. Donec vitae suscipit neque. Quisque vehicula semper dapibus. Quisque vel nisi nisl. Maecenas tempor nibh sed odio hendrerit maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc pellentesque lacus accumsan mi bibendum bibendum ut hendrerit ligula.

In ex est, egestas eget convallis id, porttitor et leo. Integer aliquam risus elit, eu viverra leo rhoncus ac. Etiam efficitur maximus ligula, ac lobortis nulla cursus at. Duis et eros lorem. Nunc dapibus augue eros, eget lobortis sapien congue a. Suspendisse sapien diam, sagittis tristique nisl non, luctus gravida sapien. Nulla at accumsan velit. Fusce ut dictum diam, eget tristique lectus. Ut at ligula non neque pharetra bibendum.

Nunc vitae tortor vel nisi egestas cursus ut nec nibh. Suspendisse eu quam dui. Proin eu condimentum nisl. Ut tincidunt urna quis quam blandit, sed tincidunt erat vehicula. In leo nisl, dictum ac accumsan a, efficitur sed felis. Nunc auctor vestibulum dui vitae dapibus. Mauris vel convallis est, eu interdum odio. Nam congue suscipit suscipit. Suspendisse nec nulla sed justo porttitor laoreet in a arcu. Suspendisse potenti. Integer non ullamcorper libero. Sed eleifend, dui in bibendum ultrices, risus nulla imperdiet sapien, sit amet scelerisque nibh nisi vitae mi. Mauris pellentesque sagittis quam vitae mollis. Aliquam mollis enim eu leo bibendum mollis non vulputate nisl. Integer ac libero ex.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In aliquet lorem pulvinar scelerisque gravida. Nam efficitur urna nec lectus lacinia consequat. Aenean sollicitudin orci a dui tincidunt, sit amet commodo massa aliquam. Sed ullamcorper tincidunt neque vel auctor. Etiam ullamcorper nisl quis placerat gravida. Proin odio libero, consectetur scelerisque libero et, convallis sodales dui. Maecenas varius, nisl eget tincidunt auctor, magna nisi consequat est, sit amet porttitor dolor ipsum quis lacus. Ut interdum leo sit amet sem aliquet commodo. Donec lobortis ipsum tortor, at scelerisque ante gravida nec. Nulla consectetur est sit amet justo rutrum, at dignissim metus interdum. Nunc ultrices augue eu dui ultrices, a ullamcorper nibh ullamcorper. Sed odio felis, eleifend non vulputate at, porttitor sed enim. Mauris in sodales arcu, ut scelerisque orci.

Curabitur viverra justo nec leo tincidunt fermentum. Nunc volutpat magna nisi, in convallis est hendrerit sed. Phasellus non justo porta, volutpat dolor nec, placerat felis. Nulla porttitor, ligula nec fringilla aliquet, dolor metus aliquam eros, nec faucibus nulla quam non ipsum. Nullam lacinia luctus elit, non ultricies orci. In sit amet molestie quam. Vestibulum molestie tellus augue. Praesent viverra tristique nisl non cursus.

Aliquam ex felis, viverra nec ex ut, venenatis condimentum arcu. Etiam pulvinar consequat faucibus. Proin eu tempor dolor. Vestibulum auctor et velit a aliquet. Maecenas nec interdum felis. Donec scelerisque enim vitae egestas auctor. Sed vel nibh bibendum, euismod ante posuere, ornare erat. Praesent luctus arcu eu nisi aliquet malesuada. Nam a placerat massa, nec egestas ligula.

Phasellus sit amet malesuada leo. Donec vitae nisl nisl. Cras et facilisis velit. Cras a dolor quam. Mauris sodales ut felis porta interdum. Cras non nisl consequat felis fringilla semper. Duis feugiat elementum dui, id mollis sem ultrices nec. Fusce varius finibus leo eu congue. Praesent non pellentesque arcu. Curabitur mi justo, lobortis vitae imperdiet vel, ullamcorper id risus. Pellentesque eget tempor erat, id bibendum neque. Integer congue consequat risus eu aliquet. Aliquam facilisis rutrum est quis venenatis. Mauris a pretium urna. Curabitur non dignissim mi.

Integer tempor consectetur consectetur. Proin dolor lorem, mollis in ipsum porttitor, porta posuere diam. Sed vel interdum risus, id maximus diam. Phasellus pulvinar eleifend porta. Aenean est augue, vestibulum at turpis nec, tempus efficitur massa. Curabitur tempor ac est nec gravida. Praesent condimentum efficitur neque sed rutrum. Phasellus accumsan diam id cursus pharetra. Sed ac ornare eros. Integer tincidunt sed nibh sit amet sodales. Donec sit amet vehicula erat. Nam tristique metus et tellus luctus consectetur. Nulla maximus vestibulum facilisis. Etiam sit amet viverra dolor.

Phasellus at purus at turpis gravida aliquet pulvinar sed enim. Suspendisse eleifend ipsum lectus, ac tincidunt mi accumsan quis. Donec porta ante at massa posuere, vitae dapibus velit consectetur. Aliquam eget nulla quis arcu posuere consectetur. Nullam eu orci nec quam auctor varius id et justo. Aliquam erat volutpat. Praesent pellentesque dui vitae augue volutpat, a aliquet odio posuere. Duis non faucibus purus, sit amet aliquam mauris.

Fusce vitae nisi tincidunt, malesuada ipsum eu, aliquet purus. Curabitur gravida risus eleifend, accumsan arcu eget, vestibulum orci. Donec turpis arcu, ultricies eget enim nec, tincidunt vestibulum tortor. Quisque quis tellus dictum, tempor felis nec, pretium lorem. Vivamus sem nulla, dignissim eu ultricies quis, malesuada eget leo. Suspendisse id iaculis purus, vitae maximus mauris. Duis in ligula et justo tincidunt consectetur. Integer placerat nibh sed egestas efficitur. In pellentesque in felis tempus malesuada. Fusce aliquet lacinia erat, eu varius turpis vestibulum a. Nam mattis volutpat felis, vel consequat augue consequat vel. Donec fermentum, enim non imperdiet eleifend, felis risus feugiat mauris, ac volutpat nisi turpis vitae felis. Pellentesque risus neque, fringilla vel tristique eu, suscipit vitae libero. Donec ut pellentesque nulla. Donec semper ullamcorper placerat. Vivamus feugiat suscipit risus a rutrum.

In hac habitasse platea dictumst. Donec non lacus at libero consequat pretium. Donec rhoncus ultricies velit, at aliquet mauris rutrum ac. Nulla condimentum tristique felis vitae egestas. Donec porta arcu ac arcu maximus condimentum. Aenean efficitur nisl massa, ut pulvinar nisi elementum non. Aenean id orci metus. Proin a consectetur ligula. Vestibulum quis magna ac lorem accumsan maximus. Praesent imperdiet est sed arcu pulvinar viverra. Nullam ullamcorper nulla non scelerisque cursus. Sed sodales luctus ex in mollis. Mauris et mattis libero. Pellentesque congue mollis orci ut malesuada. Duis justo nibh, posuere ac congue ac, finibus varius tellus.

Quisque vitae mauris dignissim enim vulputate pharetra. Aenean vestibulum sapien mi, id pellentesque odio imperdiet vitae. Quisque porta quam id sapien sollicitudin vulputate. Morbi vel odio mattis, aliquam enim eu, ornare nulla. Phasellus aliquam vehicula sapien. Suspendisse neque dui, auctor nec eros et, pretium luctus nisi. Nullam sed dolor varius, molestie mi sit amet, interdum nunc. Sed dapibus massa in nunc interdum, in vulputate tellus suscipit. Aliquam erat volutpat. Nunc vitae consectetur nibh.

Nunc sit amet arcu neque. Suspendisse molestie ipsum elit, non suscipit augue accumsan sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam nisl dui, molestie quis elit in, fermentum rutrum dolor. Sed sollicitudin libero eu risus tristique malesuada. Donec ut tellus imperdiet, vestibulum enim et, elementum enim. Nunc rutrum volutpat erat, ut porta sem viverra non. Phasellus id volutpat tortor, eget tincidunt leo. Sed ac ante a nibh vulputate ultricies. Etiam tempor porta metus, eu faucibus tellus cursus vel. Integer bibendum odio sit amet ligula volutpat feugiat.

Aliquam vitae aliquam diam, nec ullamcorper est. Maecenas suscipit molestie sapien et vehicula. Proin vehicula vulputate laoreet. Fusce sit amet dui tincidunt, rutrum quam eget, vulputate mi. In efficitur convallis facilisis. Etiam nec urna ut enim bibendum aliquam. Donec vitae sem dui. Suspendisse leo augue, semper id dignissim varius, gravida ac massa. Ut sed purus aliquam, mattis turpis ac, rhoncus quam. Mauris sem nulla, aliquam tincidunt nisl eget, varius ultricies enim. Donec sed sollicitudin felis. Morbi lacus felis, ultrices quis ullamcorper ac, euismod at dui. Sed faucibus commodo nisi, in vestibulum turpis.

Sed mauris sem, porttitor ac tincidunt at, consequat id ante. Donec sollicitudin rutrum tincidunt. Donec aliquam justo in urna aliquet gravida. Praesent venenatis dolor sapien. Nunc rhoncus viverra urna in congue. In nec ipsum quis sem facilisis luctus. Pellentesque egestas augue nunc, sed porta sapien semper vel. Integer eu tincidunt ligula, at facilisis magna. Nunc vitae magna in leo faucibus accumsan quis quis eros. Suspendisse a arcu eleifend, tincidunt lorem eget, varius massa.

Vestibulum at rhoncus augue. Donec consectetur aliquam consectetur. Maecenas aliquet elementum eros vitae malesuada. Maecenas venenatis at nisi eget finibus. Curabitur non egestas sem, et luctus massa. Sed convallis nunc felis, sed dapibus velit faucibus vitae. Nullam a rutrum sapien.

Nulla mauris augue, vestibulum sit amet mattis sit amet, ultricies eu leo. Cras at porttitor ipsum. Sed euismod eleifend porttitor. Vestibulum accumsan nisi massa, in ultricies risus condimentum nec. Nullam vel lobortis quam, sit amet eleifend mi. Nam sem sem, lobortis at leo non, tincidunt rutrum est. Vestibulum pharetra faucibus erat vitae commodo. Quisque lacinia neque at massa tristique tempor nec a dui. Cras mi augue, ornare ac faucibus ac, pellentesque vitae ipsum. In elementum purus sit amet lacus tempor, laoreet ullamcorper lorem blandit. Vestibulum tincidunt auctor arcu id hendrerit. Vivamus euismod nibh luctus lorem egestas pulvinar. Aliquam erat volutpat. Ut hendrerit odio in turpis consectetur, id hendrerit nunc imperdiet. Aenean mi dui, ultricies in urna id, tincidunt malesuada ligula.

Quisque imperdiet quis diam eget luctus. Nam aliquet libero id rhoncus cursus. Aliquam turpis tortor, pulvinar nec ullamcorper a, gravida vel nibh. Nunc quis mattis augue. Sed ultricies quis augue quis cursus. Pellentesque massa neque, efficitur sit amet orci in, venenatis pretium nisi. Sed non pulvinar mi. Suspendisse vulputate posuere mi id sagittis. Nam porta, augue nec lobortis aliquam, elit nisi accumsan felis, eget tristique tortor ante in ante. Phasellus lacinia at justo vitae dignissim.

Etiam et nunc in ligula bibendum finibus. Morbi vulputate, ligula sed sagittis ultrices, ante mauris lobortis elit, at elementum dui lectus ut sapien. Fusce ac purus facilisis augue maximus fermentum auctor vel diam. Integer porta sapien sed quam ullamcorper ultrices. Maecenas eleifend posuere ligula, vel aliquam augue ornare rutrum. Proin sagittis sem risus, non volutpat diam gravida ut. Mauris tortor tellus, feugiat nec gravida ac, interdum non tellus. Donec tristique a elit sit amet ornare.

Nam pulvinar, augue non rhoncus dapibus, nisl ex consequat ipsum, vitae aliquet arcu elit non dui. Ut sed luctus massa, id lacinia tellus. Integer faucibus purus et tincidunt porttitor. Donec tempor lectus ex, quis vehicula tortor hendrerit sit amet. Praesent mollis est et lectus aliquam sagittis. Suspendisse massa orci, feugiat quis dolor posuere, posuere convallis magna. Donec rhoncus orci ligula, vitae accumsan elit facilisis nec.

Sed dui elit, maximus sit amet rutrum sit amet, accumsan et urna. Vivamus nisi tortor, hendrerit ut rhoncus sit amet, vulputate ac massa. Aenean mattis sagittis arcu in imperdiet. Mauris eu eros nunc. Pellentesque vestibulum egestas ex non blandit. Phasellus dignissim, neque a finibus dapibus, turpis turpis vestibulum arcu, nec tempus ligula ante nec lorem. Maecenas pharetra leo a sagittis sodales. Quisque imperdiet a mi eget venenatis. Curabitur a elementum tortor. Nunc pretium elementum cursus. Donec congue bibendum elit, ut viverra ex vehicula vel.

Donec vel blandit lorem. Phasellus vitae neque in ipsum suscipit finibus ut at nunc. Nam ac quam varius, pulvinar turpis vel, sodales erat. Nunc iaculis sed sapien nec molestie. Quisque eros augue, finibus eget lorem at, lacinia elementum nulla. Donec rhoncus consectetur lacinia. Etiam interdum dictum molestie. Ut pulvinar nisi justo, in interdum ipsum dapibus a. Vivamus id aliquet nisi. Nulla sit amet eleifend mauris. Nam congue, est nec sodales elementum, massa ex dictum lacus, vitae aliquam elit lacus ac urna. Donec est arcu, vehicula et enim quis, tempor vestibulum nisl. Quisque gravida molestie est, sit amet lacinia felis molestie eget. In lacinia sagittis ipsum. Donec commodo, purus in iaculis gravida, arcu mauris hendrerit nunc, a auctor augue leo at lectus. Suspendisse ut suscipit dui.

Etiam in sodales orci, vitae tempor ipsum. Morbi neque metus, cursus ac nisl vel, cursus faucibus libero. Cras quis ipsum ac sapien vehicula feugiat in faucibus nisl. Donec libero nisi, lobortis nec lectus sed, aliquam pulvinar dolor. Nulla facilisi. Aenean in ligula quam. Integer aliquet felis velit, non malesuada justo interdum non. Nam ac turpis pretium, rutrum lectus sed, fringilla tortor. Phasellus ut fermentum massa.

Nulla ac purus eu lacus posuere varius sit amet at lorem. Sed consequat blandit tortor, vel maximus erat vestibulum eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec fermentum erat non risus semper, nec laoreet tellus varius. Nam condimentum erat sed neque porttitor aliquet. Suspendisse porta eleifend purus, sed euismod risus volutpat placerat. Nunc maximus sodales velit vitae consectetur. Vivamus sit amet laoreet dui.

Integer at augue sed diam gravida finibus non vel nisl. Duis elementum luctus imperdiet. Aenean viverra nisl id metus bibendum porttitor. Nunc eget augue nec nisl pulvinar interdum vel nec nisi. Etiam mauris massa, rutrum vel porttitor ut, congue non massa. Duis sit amet risus sit amet nibh accumsan sagittis. Etiam luctus egestas ipsum quis posuere. Integer fermentum, augue vel sollicitudin finibus, neque turpis efficitur tortor, sed ullamcorper nibh felis quis diam. Duis velit lectus, maximus hendrerit tempor eu, venenatis et quam. Mauris vulputate, odio quis varius dictum, sapien orci feugiat magna, in lacinia sem mi suscipit justo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dapibus iaculis magna, id volutpat metus hendrerit non. Aliquam risus diam, egestas id pulvinar sed, sagittis eu velit. Sed at venenatis risus, id rhoncus enim. Nullam lorem sapien, posuere eget mauris in, feugiat facilisis elit. Quisque est leo, accumsan in tincidunt in, molestie eget justo. In ultricies leo eu rutrum aliquam. Sed consectetur dui eu sagittis posuere. In et viverra nisl, quis feugiat lectus. In molestie pellentesque mi ac euismod.

Quisque urna sapien, blandit non odio id, eleifend rutrum lorem. Duis eros ex, placerat dapibus augue nec, ornare auctor diam. Ut vitae nulla consequat, molestie velit semper, egestas nisl. Donec efficitur tellus est, sit amet ultricies lorem cursus ornare. Integer tempus ligula a quam fermentum, a porta augue tempus. Nunc tristique odio vulputate malesuada rhoncus. Vestibulum dictum suscipit nisi, et scelerisque massa pretium in. Sed blandit ultricies nunc, eget lacinia est elementum nec. Sed hendrerit metus eros, porttitor scelerisque massa posuere quis. Aenean convallis ante vitae finibus tincidunt. Ut vehicula pulvinar nibh. Nam gravida libero nec dapibus elementum. Nullam auctor, ante fermentum condimentum dignissim, mi nisi pellentesque ligula, ac interdum risus magna id libero.

Nulla mattis justo vitae neque feugiat, in viverra justo pretium. Aliquam eu lorem nec lectus posuere consectetur. Nullam congue ligula eros, at cursus nisi consequat id. Curabitur rhoncus malesuada urna. Curabitur vel scelerisque erat. Quisque tortor nulla, finibus ut porta quis, venenatis eu augue. Vivamus pharetra fermentum aliquam. Mauris at tortor velit. Vivamus pretium sed quam sit amet dictum.

Aenean blandit at enim id venenatis. Duis pulvinar, nisl non lobortis fringilla, ipsum nibh hendrerit neque, at posuere augue justo at lectus. Mauris sed molestie libero. Integer finibus dignissim sollicitudin. Nunc malesuada, erat vitae posuere euismod, velit nisl laoreet velit, sed lobortis nulla nunc efficitur magna. Maecenas venenatis tempus luctus. Nunc accumsan lacus mattis nisl dapibus, vel malesuada metus tincidunt. Fusce sagittis, lorem quis porttitor efficitur, ipsum metus tincidunt ex, et finibus ligula lacus pretium lectus. Aenean hendrerit magna nulla, eget mollis risus bibendum et. Aliquam erat volutpat. Aenean nec quam risus. Aenean a mauris non mi tincidunt ullamcorper in vel mauris. Nunc euismod nulla dolor, ut ullamcorper eros blandit at. Nam non dapibus massa.

Morbi luctus rhoncus facilisis. Sed leo nunc, placerat vitae porttitor ut, rutrum vel massa. Integer purus dolor, congue vitae ante et, sagittis molestie lorem. Sed sed elit nec leo volutpat rhoncus. Pellentesque tempor ornare lorem, ut consequat quam iaculis accumsan. Pellentesque eleifend mattis lobortis. Suspendisse euismod porttitor ante id sagittis.

Etiam tristique vehicula orci. Praesent consequat felis vel tempus placerat. Fusce vitae ipsum ipsum. Vestibulum dui purus, fringilla eu malesuada eget, imperdiet vitae nisi. Proin nec varius nisi. Maecenas ac nisl ac enim hendrerit tempus. Vestibulum sed diam velit. Pellentesque suscipit lorem quis massa lacinia, vitae lacinia dolor dignissim. Etiam non blandit nibh, eu ultricies turpis. Quisque aliquet mi enim, et semper lorem vestibulum eget. Curabitur iaculis facilisis lectus, vel scelerisque mauris auctor rhoncus. In congue, est a condimentum aliquet, ante enim interdum dolor, sed faucibus orci ligula vel quam. Nullam sit amet mauris a neque laoreet placerat ac vel tellus.

Sed ligula risus, rhoncus vel tincidunt eu, fringilla quis justo. Praesent sem justo, gravida sed maximus in, mattis gravida nunc. Integer in augue tincidunt, lacinia sapien at, mollis libero. Nulla mollis sem non interdum tempor. Aenean quis tempus risus. Nullam sollicitudin est justo, quis congue ligula pretium porttitor. Sed porta, velit at dignissim vehicula, lacus nulla aliquet purus, ac fringilla mi dolor ac urna. Aenean eget hendrerit nibh. Aliquam auctor urna dolor, eu maximus eros semper vitae. Nunc eu massa tortor. Nullam luctus sapien quis condimentum imperdiet. Vestibulum tincidunt fringilla sem, non tincidunt mauris porttitor id.

Phasellus dui augue, accumsan id venenatis id, sodales vitae ante. Curabitur ac elementum lorem, id euismod libero. Sed mauris metus, dapibus a egestas a, volutpat in lorem. Vestibulum id ex nunc. Proin sollicitudin fringilla rutrum. Vivamus diam justo, consequat vitae viverra ac, fermentum eu enim. Phasellus eu feugiat sapien. Cras efficitur a elit id convallis. Donec efficitur eget ligula ut sollicitudin. Ut lacinia dapibus nunc, eget interdum tellus vestibulum quis.

Etiam eget eleifend ex, nec bibendum dui. Vestibulum molestie dolor vel pulvinar gravida. Sed suscipit, justo et vestibulum aliquet, risus nunc varius nibh, et mattis dolor felis vitae eros. Integer ante quam, consectetur ut arcu eu, bibendum fermentum velit. Nulla sed rutrum nisl, sit amet tincidunt dolor. Maecenas tempor, eros in laoreet ultricies, arcu magna aliquet nisi, non ultricies odio risus a dui. Vestibulum sit amet arcu at ex hendrerit facilisis sed porttitor neque.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus faucibus vestibulum sollicitudin. Donec et nisl id velit cursus facilisis quis et ligula. In quis massa sit amet lectus dapibus commodo vel in nunc. Maecenas ac egestas odio, id tempor ex. Proin vel odio in lacus convallis cursus. Praesent viverra fringilla pulvinar. Vivamus luctus leo sed libero tristique, quis tempor risus ornare. Sed dignissim sed massa sed sodales. Vivamus quis elementum augue. Vivamus vestibulum, orci vel lobortis pretium, enim ante rhoncus ipsum, sed vehicula nisi arcu cursus nisl.

Vestibulum congue convallis neque, quis pellentesque ex eleifend sit amet. Vestibulum vitae commodo diam. Proin ex eros, sagittis ac iaculis eu, dignissim ac nibh. Ut sit amet tellus sit amet sapien tempor viverra. Nam iaculis ex vitae arcu porta rhoncus. Nulla faucibus tempus leo, a mattis mi cursus quis. Pellentesque a mi posuere, tempor ante molestie, sollicitudin lacus. Vivamus quis justo suscipit diam molestie interdum. Quisque laoreet ante a mattis aliquet. Curabitur rhoncus posuere diam nec vestibulum. Praesent sapien turpis, luctus a dui porta, gravida facilisis libero. Phasellus sagittis tempus massa, ut auctor ligula vehicula sit amet. Cras sagittis libero non sem consequat tincidunt. Sed hendrerit ipsum nec condimentum consequat. Sed eget urna non risus rutrum lacinia.

Pellentesque quis suscipit mi. Ut fringilla ut enim quis varius. Etiam in dapibus turpis. Ut fermentum et dui at facilisis. Etiam felis orci, mollis feugiat diam nec, lobortis vehicula erat. Donec consequat, dolor sit amet accumsan sollicitudin, velit turpis eleifend ipsum, ut commodo ante orci eget tortor. Nam volutpat consectetur ligula sed facilisis.

Donec nec dui velit. Donec pellentesque magna ut quam venenatis lacinia. Sed facilisis feugiat enim, non dictum tellus fringilla cursus. Vestibulum accumsan dolor porta commodo pretium. Nam lectus nulla, convallis a erat vel, dapibus convallis sapien. Cras quis velit nec nunc congue rutrum in quis nisl. Vivamus egestas massa eu ligula dapibus laoreet.

Mauris ut mauris non neque rhoncus malesuada nec ut odio. Morbi commodo sagittis mauris, vitae rutrum justo varius id. Curabitur vitae imperdiet odio. Sed eget ipsum dui. Vestibulum et semper tellus, quis tempus nisl. Phasellus vel ultricies dolor. Donec interdum, nulla vel efficitur mattis, lacus turpis pharetra risus, euismod commodo ipsum libero at justo. Vestibulum scelerisque urna vitae sem tristique, a semper urna auctor. Integer condimentum mi at tortor congue, sed aliquet elit finibus. Duis efficitur rhoncus erat id gravida. Cras vel molestie dui, sed viverra justo. Donec condimentum ligula scelerisque metus tempus volutpat. Nullam nec erat maximus, auctor diam non, congue purus. Sed semper mauris non sapien venenatis elementum. Etiam iaculis rhoncus risus. Sed eu urna lectus.

Quisque pharetra placerat dolor, sed finibus odio porta at. Vivamus feugiat nulla ut posuere semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam at libero egestas, rutrum massa ac, euismod lacus. In metus massa, ultricies sed blandit in, viverra a ex. Nulla vitae diam est. Aenean lobortis turpis turpis. In venenatis aliquam posuere. Pellentesque gravida eu arcu quis faucibus. Pellentesque ultrices lacus leo, vitae ultricies lectus consectetur at. Vestibulum suscipit lectus et malesuada varius. Praesent at aliquet eros. Aenean non mauris id mauris efficitur ultrices nec a purus. Maecenas diam leo, dignissim ut condimentum vitae, luctus vitae augue.

Curabitur sapien lectus, molestie ac odio at, eleifend ultrices lacus. Proin suscipit ut tortor et malesuada. Suspendisse ipsum sem, ultricies lobortis mollis ac, volutpat ac turpis. Ut blandit orci pharetra purus posuere, ac ornare ipsum efficitur. Maecenas in facilisis leo. Sed ultricies condimentum dui auctor faucibus. Vivamus justo felis, sollicitudin sit amet massa sit amet, dapibus ornare tellus. Aenean tincidunt tortor pharetra mauris lobortis, nec porta tellus dictum. Praesent porttitor massa aliquam libero vulputate, ut sagittis metus vestibulum. Suspendisse tincidunt, erat sit amet blandit interdum, metus arcu sodales augue, sit amet volutpat libero odio sed leo. Sed ornare lacinia nulla, interdum hendrerit elit pretium eget.

Aliquam sit amet eros bibendum, suscipit ligula et, porta massa. Curabitur eu vehicula massa. Donec vitae rhoncus felis. Vivamus turpis enim, blandit sit amet elit et, aliquet fringilla diam. Mauris rhoncus feugiat porttitor. Sed convallis justo in scelerisque laoreet. Quisque odio ipsum, maximus sed rhoncus nec, pretium fringilla ipsum. Suspendisse luctus venenatis tellus, non faucibus justo porttitor ut. Aliquam enim ipsum, ultrices at velit tempus, malesuada tincidunt magna.

Proin volutpat, justo et posuere bibendum, tortor lorem hendrerit lectus, eget fringilla mauris enim vitae orci. Fusce id purus sed arcu egestas bibendum. Duis sed massa arcu. Curabitur sodales orci at nibh maximus porttitor. Vivamus suscipit massa quis erat porttitor euismod. Proin eu mi vitae felis vehicula tempor vitae sit amet ligula. Quisque in mi egestas, hendrerit dui ac, malesuada nulla. Curabitur malesuada bibendum elit eget scelerisque. In viverra mollis dolor, id finibus elit tristique quis. Nullam fermentum in eros sit amet rutrum. Maecenas in orci magna. Nunc sed tellus nec metus ultricies scelerisque vitae sit amet nibh. Vivamus venenatis bibendum nisi ac scelerisque. Sed feugiat risus quis vulputate viverra. Nulla lobortis ut nisl sed porttitor. Praesent vitae diam sit amet justo pretium hendrerit ac ut erat.

Proin mollis lorem diam, vitae molestie dui iaculis at. Fusce odio purus, molestie in orci pellentesque, varius varius ligula. Mauris eros ligula, feugiat vitae varius at, imperdiet at tellus. Suspendisse auctor mauris pretium, ullamcorper elit non, egestas enim. Vestibulum non libero pharetra, condimentum eros id, imperdiet ipsum. Mauris egestas viverra iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent at fringilla nulla. Mauris tristique lectus in elit laoreet pulvinar.

Suspendisse laoreet pulvinar dolor et gravida. Nunc ut neque maximus, rhoncus elit ac, ultrices enim. Pellentesque vel mattis erat. Vestibulum molestie convallis sem, imperdiet malesuada nulla laoreet eget. Mauris ut pellentesque risus. Proin at mauris et nisi vehicula iaculis non eu turpis. Aenean condimentum eget risus nec fermentum. Proin hendrerit pharetra odio, at lacinia sem. Suspendisse viverra libero felis, a commodo orci egestas ac. Nunc augue lorem, tempus congue efficitur at, mattis lobortis ante. Sed feugiat fringilla semper.

Aenean ornare fringilla ligula eu scelerisque. Vestibulum maximus fringilla turpis, eget aliquet tellus. Duis tempus, velit at semper convallis, nunc lectus bibendum urna, vel sollicitudin elit lorem in velit. Vestibulum at iaculis ex, nec vehicula diam. Curabitur laoreet orci sed maximus semper. Aenean ultrices nec risus ut tincidunt. Integer tincidunt ornare quam nec egestas. Donec nec tempus turpis. Cras mattis felis felis, sed molestie arcu pulvinar sed. In egestas diam libero, quis euismod purus elementum eget.

Curabitur bibendum maximus convallis. Nulla ac tristique nisl, vel semper urna. Sed vel iaculis elit, finibus viverra quam. Sed sit amet ipsum vitae elit congue dignissim. Etiam eget elementum felis. Nunc luctus urna id ex lobortis, sit amet porttitor tortor feugiat. Nam sem leo, dictum eget nulla nec, porttitor luctus tortor. Praesent tincidunt luctus dolor, eget eleifend mauris placerat ut. Fusce scelerisque mi ac pellentesque ultricies. Sed accumsan aliquet diam.

In vitae semper nulla, vel malesuada mauris. Praesent maximus quam nisl, quis lacinia ante luctus vitae. Sed ac enim non est rutrum viverra. In ex lectus, bibendum eget ullamcorper ut, tempus ac sem. Cras malesuada, sapien eu pellentesque laoreet, mauris felis venenatis arcu, in dignissim metus magna a purus. Integer ut egestas diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sollicitudin erat molestie orci rutrum varius. Ut at erat id dui tempus iaculis. Fusce varius turpis quis maximus egestas. Curabitur vitae gravida elit, imperdiet dapibus sapien. Ut eget ullamcorper lectus. Cras ac risus mi. Nulla id placerat enim. Sed at congue felis. 
"""


print("Porównanie tekstu źródłowego i tekstu po kompresji i dekompresji: {}".format(
    dekompresja(kompresja(a)) == a))


# Link do tekstu:
# https://www.lipsum.com/feed/html
