#!/usr/bin/env python3

import os
import argparse
import subprocess


def shell(prog):
    return subprocess.run(prog, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def run_profiler(prog, proc):
    callgrind = shell(['valgrind', '--tool=callgrind',
                       '--toggle-collect=' + proc,
                       '--callgrind-out-file=callgrind.out'] + prog)
    if callgrind.returncode:
        print(callgrind.stdout.decode())
        raise SystemExit('Your program gives wrong answer!')

    annotate = shell(['callgrind_annotate', 'callgrind.out'])

    section = None
    procinst = {}
    for line in annotate.stdout.decode().splitlines():
        if not line or line.startswith('---'):
            continue
        if section == 'Ir':
            insn, loc, _ = line.split()
            procinst[loc] = int(insn.replace(',', ''))
        if 'Ir' in line and 'file:function' in line:
            section = 'Ir'

    os.remove('callgrind.out')
    return procinst


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Run program and check number of executed instructions.')
    parser.add_argument('--procedure', type=str,
                        help=('source file name and procedure name '
                              'separated by colon'))
    parser.add_argument('--max-insns', type=int,
                        help=('maximum number of executed instructions '
                              'for given procedure name and source file'))
    parser.add_argument('program', type=str, nargs='+',
                        help='program with command line arguments')
    args = parser.parse_args()

    source, procedure = args.procedure.split(':')

    profile = run_profiler(args.program, procedure)
    insns = profile.get(args.procedure, 0)
    if insns == 0:
        raise SystemExit('Procedure "%s" not found in "%s"!' % (
                         procedure, source))
    if args.max_insns and insns > args.max_insns:
        print('Executed instructions: %d.' % insns)
        raise SystemExit('Your program takes to much time to run!\n'
                         'Exceeded limit of executed instructions: %d!' %
                         args.max_insns)
